
myStage:
  myStep:
    container:
      image: ubuntu:20.04
      shell: bash
      cmds:
        - |
          echo Start
          for x in {1..50}; do
            for i in {1..20}; do
              echo $i
              sleep 0.1s
            done
            sleep 5s
          done
          echo Done
